DEFAULTS = {
    "batch_size": 16,
    "bert": "bert-base-uncased",
    "clip_value": 1.0,
    "dropout": 0.0,
    "embed_dim": 256,
    "encoder": "gru",
    "epochs": 20,
    "hidden_dim": 128,
    "lr": 5e-5,
    "main_only_epochs": 0,
    "num_layers": 2,
    "num_restarts": 1,
    "patience": 5,
    "print_every": 50,
    "save_path": None,
    "stress_weight": -1,
    "tolerance": 1e-4,
    "trials": 20
}
